version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev  # 使用你现有的 Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - backend-net

  nginx:
    image: nginx:1.26
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/app/uploads
    depends_on:
      - backend
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
